version: '3'
services:
  alice:
    build: 
      context: .
      dockerfile: alice/Dockerfile
    ports:
      - 19001:19001
      - 18884:18884
    networks:
      local:
        ipv4_address: 10.10.0.10
    volumes:
      - daemon-config:/config
  electrs:
    build:
      context: .
      dockerfile: electrs/Dockerfile
    ports:
      - 3002:3002
    networks:
      local:
        ipv4_address: 10.10.0.11
    volumes:
      - daemon-config:/config

networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24

volumes:
  daemon-config:
